### ISSUE TITLE
Fails to Build on Apple Silicon

### ISSUE THREAD

**Issue by alexclst** [biscuitehh/pam-watchid#11]
When I try to build this on an Apple Silicon Mac it fails to build with the following error:

```
swiftc watchid-pam-extension.swift -o pam_watchid.so -target x86_64-apple-macosx10.15 -emit-library
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.15'
make: *** [all] Error 1
```

The `TARGET` needs to be platform-sensitive and use the right value for the given OS and architecture, I think.

**Comment by ReubenBTalbott** [comment]
Someone in issue #7 got it to run on Apple Silicon by changing the build architecture in the make file.
