### ISSUE TITLE
Asks for password and watch

### ISSUE THREAD

**Issue by mneumark** [biscuitehh/pam-watchid#2]
I tried running this. I still get a password prompt with no apple watch prompt. Then after entering the password the apple watch prompt appears and if the password is wrong, it doesn't authenticate. Am I doing something wrong?

**Comment by ybrodala** [comment]
Hi, I've had the same issue. What fixed this for me was just to put the pam_watchid.so line as the first entry in the file. (Apparently the rules are applied from top to bottom)

**Comment by mneumark** [comment]
That fixed it! Thanks!
