### ISSUE TITLE
Operation not permitted.

### ISSUE THREAD

**Issue by theLMGN** [biscuitehh/pam-watchid#6]
I had to append a '.2' to the end of the file name adding to the PAM config, however whenever I try to run sudo after setting this up, I just get a PAM operation permitted error. I figured out how to revert changes (use Finder) but I can't get this library to work.

**Comment by Aayush9029** [comment]
try this

`open /etc/pam.d`

> right click sudo filename > get info ~scroll down (click lock) change from readonly to read and write 

> edit the file once again ~ revert back to read only

**Comment by theLMGN** [comment]
@Aayush9029 
>  I figured out how to revert changes (use Finder) but I can't get this library to work.

**Comment by tthoma24** [comment]
Are you able to edit /etc/pam.d/sudo with a command-line text editor, like vi or emacs?

**Comment by theLMGN** [comment]
> Are you able to edit /etc/pam.d/sudo with a command-line text editor, like vi or emacs?

Yes.

**Comment by tthoma24** [comment]
And once you do that, what happens? What is the error you run into when running a command with sudo?

**Comment by theLMGN** [comment]
Operation not permitted from PAM.

**Comment by tthoma24** [comment]
It’s working okay for me. Would you be able to provide the following:

-OS major and minor version (e.g 10.15.5)
-Contents of your /etc/pam.d/sudo
-The command you run and the exact output from the terminal when you run it

**Comment by theLMGN** [comment]
Nevermind, it just started working now.
